### DISCUSSION TITLE
i18n: Add CSV translation support

### DISCUSSION THREAD

**Discussion by JDavidVR** [withastro/roadmap#1083] [Proposal]
### Body

# Summary

Add CSV translation support

# Background & Motivation

Hi, I'm coming from Magento world and worked with multi-languages stores.

In Magento the default language is english and for translation it uses a .CSV file, for example if I want to translate to Spanish I have to create a  `i18n/es_ES.csv` file and its content would be:

```CSV
"My Account", "Mi Cuenta"
Dahsboard,"Panel de Control"
"Sign In", "Iniciar Sesion"
New, Nuevo
"Welcome %1", "Bienvenido %1"
```

To make translations work in templates and php clases, there is global funcion `__("Text Here")`

In template

```phtml
<button> 
<?php echo __("My Account") ?>
</button>
```

In PHP classes, for dynamic texts
```PHP
public function getWelcomeMsg($name) {
    return __("Welcome %1", $name)
}
```

I've been investigating how translationg works on another ecommerce platform and they look a bit complex

Shopware 6.0 uses .json https://github.com/shopware/translations/blob/main/translations/es-ES/Platform/Administration/administration.json

```json
{
    "entityCategories": {
        "additional_privileges": {
            "entities": {
                "api_feature_flag_toggle": "Cambiar el indicador de función de la API",
                "api_service_list": "API de listado de servicios",
                "api_service_toggle": "API de conmutación de servicios"
            },
            "title": "Permisos adicionales"
        }
    }
}
```

Sylius 2.0 uses .yml https://github.com/Sylius/Sylius/blob/dd339a59698e898d02e12f34e14c4a114bc87270/src/Sylius/Bundle/AdminBundle/Resources/translations/messages.es.yml

```yml
sylius:
    email:
        shipment_confirmation:
            subject: 'Confirmación del envío'
    menu:
        admin:
            main:
                catalog:
                    association_types: Tipos de asociación
                    attributes: Atributos
                    header: Catálogo
```

Laravel uses .json: https://github.com/Laraveles/spanish/blob/master/resources/lang/es.json

```json
{
    "E-Mail Address": "Correo electrónico",
    "Password": "Contraseña",
    "Remember Me": "Recuérdame",
}
```

# Goals

- CSV allows an easier translation, they can be edited on any spreadsheet software
- Static content should keep separete files
