### DISCUSSION TITLE
[Blog theme] What about to add `color-scheme` property to support dark mode

### DISCUSSION THREAD

**Discussion by pavelkeyzik** [withastro/roadmap#389] [Proposal]
## Proposal

The official [blog theme](https://github.com/withastro/astro/tree/main/examples/blog) comes with a tiny CSS file, and everything is in light mode. The proposal is to add support for switching between dark and light mode. As the initial version doesn't have any custom UI elements, it should be easy to add this support.

## Engineering details

In styles.css I added this code

```css
/* Main changes */
html {
  color-scheme: dark light;
}

/*
  Additional changes to fix issues with some colors. It's just for demo purpose,
  but we could refactor this much with CSS variables
*/
@media (prefers-color-scheme: dark) {
  body {
    background-color: #111;
    color: #9d9d9d;
  }
  h1,
  h2,
  h3,
  h4,
  h5,
  h6,
  strong,
  b {
    color: #7c7c7c;
  }
  a {
    color: #3273dc;
  }
  code {
    background-color: #1c1c1c;
  }
  blockquote {
    border: 1px solid #333;
    color: #7c7c7c;
  }
}

@media (prefers-color-scheme: light) {
  body {
    background-color: #fff;
    color: #444;
  }
  h1,
  h2,
  h3,
  h4,
  h5,
  h6,
  strong,
  b {
    color: #222;
  }
  a {
    color: #3273dc;
  }
  code {
    background-color: #f2f2f2;
  }
  blockquote {
    border: 1px solid #999;
    color: #222;
  }
}
```

## Demo

https://user-images.githubusercontent.com/17102399/201898013-4ad6c37a-e78c-4ab1-8f90-d41066ec9c84.mp4

## What we need to discuss

- [ ] What colors we'll have, as we need to adjust them for dark theme
- [ ] In dark mode, code block doesn't look good, maybe we should do something with background
