### DISCUSSION TITLE
Support other formats in data content collections

### DISCUSSION THREAD

**Discussion by nix6839** [withastro/roadmap#704] [Proposal]
### Body

# Summary

Support other formats([TOML](https://toml.io/), [JSON5](https://json5.org/), etc.) in data content collections.

# Background & Motivation

There are so many missing features in JSON: comments, multi-line strings, datetimes, and more.
It makes it uncomfortable for users (at least me) to view data. It makes it uncomfortable for users (at least to me) to view data.
But another formats like TOML support many more features than JSON:
```TOML
# This is a comment

lines = '''
The first newline is
trimmed in raw strings.
All other whitespace
is preserved.
'''

infinite1 = inf # positive infinity
infinite2 = +inf # positive infinity
infinite3 = -inf # negative infinity

# offset datetime
odt1 = 1979-05-27T07:32:00Z
```

# Goals

- Support data formats other than JSON in data content collections.

# etc.
> User-facing APIs to introduce new data collection formats like YAML or TOML. We recognize the value of community plugins to introduce new formats, and we will experiment with a pluggable API internally. Still, a finalized user-facing API will be considered out-of-scope.

I think this topic has come up before, is there a discussion going on? <https://github.com/withastro/roadmap/issues/530>
