### DISCUSSION TITLE
Allow content collections to be a single YAML file

### DISCUSSION THREAD

**Discussion by essential-randomness** [withastro/roadmap#785] [Proposal]
# Summary

Right now, content collections of type `data` still require a new file for each collection entry. I'd love the possibility of using the same interface as data content collections, but keeping the data all in a single file.

# Background & Motivation

Sometimes each element in a content collection (especially data) only contains a small quantity of information. Currently, the structure of content collections forces a new file for each entry, and doesn't allow for smaller collections to be kept all in the same file.

I'm sure I could write my own wrapper that loads a single file and passes it through Zod so it work similarly to content collections, but I like the content collection API, and I'd love to have one single way of loading my content data. Then, if the content collection starts growing, I can switch to an entry per file later on.

This might be an abuse of the content collection API and there may be repercussions I'm not thinking about, but I thought I'd try asking anyway :) Ideally, I should be able to handle the switch from single file to multiple files seamlessly in my code, and only change the content collection configuration to load the data differently.

# Goals

- Allow to keep content collection data in a single file making it easier to manage smaller collections of data (since you don't have to jump file by file for edits)
- Allow to keep some data at the top level of the content collection folder, without needing to add a folder containing a single file
- Make prototyping with smaller content collections easier

# Example

### Streaming schedule example

For example, I recently wanted to create a "streaming schedule" content collection, where each entry would only have the following data:

```yaml
- name
- date
- category
- video_url
```

Especially now that I have only a few streams, I'd love to be able to add all the streams to a single file, rather than having to create a series of files only to write 4 lines in each.

Something like:

```yaml
- stream1_slug:
  - name: 
  - date:
  - category:
  - video_url:
- stream2_slug:
  - name: 
  - date:
  - category:
  - video_url:
...
```

This means that if I change my content collection while prototyping, I don't have to juggle making an update to e.g. 6 different files.

### Socials collection workaround example

An example of how I handled this in the past, is my "socials" content collection. Here's the full file:

```yaml
socials:
  - https://essential-randomness.tumblr.com
  - https://twitter.com/essentialrandom
  - type: mastodon
    name: the Fediverse™
    url: https://indiepocalypse.social/@essentialrandom
  - https://bsky.app/profile/essentialrandom.bsky.social
  - https://www.twitch.tv/essentialrandomness
  - https://github.com/essential-randomness
  - https://essential-randomness.dreamwidth.org/
  - https://www.youtube.com/channel/UCI_NX0PeoiWiMsHIFH0TBsw
  - https://www.patreon.com/essentialrandomness
  - https://ko-fi.com/essentialrandomness
```
and here's the definition:

```ts
const WebsitesSchema = z.enum([
  "github",
  "tumblr",
  "twitter",
  "npm",
  "web",
  "twitch",
  "mastodon",
  "dreamwidth",
  "store",
]);

export const SocialsSchema = z.string().or(
  z.object({
    name: z.string(),
    url: z.string(),
    type: WebsitesSchema.optional(),
    icon: z.string().optional(),
  })
);

export const socials = defineCollection({
  type: "data",
  schema: z.object({
    socials: z.array(SocialsSchema),
  }),
});
```

This is in a `socials/socials.yaml` file. What I'd like to have, is the ability to declare a `socials.yaml` file at the **top level** of my content folders (so no need for an extra nesting), and to export `SocialsSchema` directly, without needing to create a `z.object` that just contains an array of my socials.
